apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
  labels:
    app: auth
spec:
  type: ClusterIP
  ports:
    - port: 7001
      name: auth
      targetPort: 8001
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: backend
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: andrey4281/auth-service:0.0.1
          name: auth
          env:
            - name: RDS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-host-name
            - name: RDS_PORT
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-port
            - name: RDS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-db-auth-name
            - name: RDS_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: otus-app-config
                  key: rds-user-name
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-app-secrets
                  key: psqluserpass
            - name: JWT_PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: services-config
                  key: jwt-private-key
          ports:
            - containerPort: 8001
          imagePullPolicy: IfNotPresent